name: Release App

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Build & Release (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    env:
      GYP_MSVS_VERSION: 2022
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm config set msvs_version 2022
          npm ci --msvs_version=2022
        shell: bash

      - name: Build Frontend Web Assets
        run: npm run build

      - name: Compile & Publish App
        run: |
          if [ "$RUNNER_OS" == "macOS" ]; then
            npx electron-builder --mac --publish always
          else
            npx electron-builder --win --publish always
          fi
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
